org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true
# Meta
mod.id=pendulum
mod.name=Pendulum
mod.group=com.iafenvoy
mod.version=1.0
mod.description=Client side script executor for Minecraft.
mod.authors=IAFEnvoy
mod.repo_url=https://github.com/IAFEnvoy/Pendulum
mod.license=LGPL-3.0
mod.logo=logo.png
# Deps
deps.fabric-loader=0.17.3
# Publish
publish.curseforge=1562526